#!/bin/sh -e
DESTDIR="/opt/nightly"
TMPFILE="/tmp/nightly.tar.bz2"
LANGCODE=`env | grep LANG= | awk -F= '{print $2}' | awk -F_ '{print $1}'`
archs=`uname -m`
case "$archs" in
    i?86) archs="linux32" ;;
    x86_64) archs="linux64" ;;
    armel) archs="linuxarmel" ;;
esac

wget "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=${archs}&lang=${LANGCODE}" -O $TMPFILE
cd /tmp
mkdir -p $DESTDIR
tar xjvf $TMPFILE -C $DESTDIR --strip-components=1
rm $TMPFILE
