#!/bin/sh -e
DESTDIR="/opt/firefox-nightly"
TMPFILE="/tmp/nightly.tar.bz2"
LANGCODE=`echo $LANG | awk -F_ '{print $1}'`

if [ -f /opt/nightly ]; then
    mv -f /opt/nightly /opt/firefox-nightly
fi

case $LANGCODE in
en|es|fy|ga|zh) LANGCODE=`echo $LANG | sed -e 's/_/-/g' | awk -F. '{print $1}'` ;;
C.UTF-8|C ) LANGCODE="en-US" ;;
*) echo "$LANGCODE" ;;
esac

echo "Current Language is ⁝$LANG⁝ = ⁝$LANGCODE⁝"

archs=`uname -m`
case "$archs" in
    i?86) archs="linux32" ;;
    x86_64) archs="linux64" ;;
    armel) archs="linuxarmel" ;;
esac


wget "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=${archs}&lang=${LANGCODE}" -O $TMPFILE
cd /tmp
mkdir -p $DESTDIR
tar xjvf $TMPFILE -C $DESTDIR --strip-components=1
rm $TMPFILE
